defaults:
  - ../model@model: transformer
_target_: multistep_dynamicsdiffusion.diffusion_dx.DiffusionDx
scheduler:
  _target_: diffusers.DPMSolverMultistepScheduler
env_name: ${..env_name}
obs_dim: ${..obs_dim}
action_dim: ${..action_dim}
horizon: ${..agent.horizon}
detach_xt: true
clip_grad_norm: null
lr: 1e-4
num_inference_steps: 20
ema_rate: 0.9999